name: DAST

on:
  workflow_dispatch:
  # push: # Any branch
  # pull_request:
  #   branches:
  #     - main

jobs:
  zap_scan:
    name: ZAP Scan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - Web
          - PublicAPI
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Start the Application
        run: |
          docker-compose build
          docker-compose up

      - name: ZAP Scan ${{ matrix.image }}
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: if (matrix.image == 'Web') 'http://localhost:5106' else 'http://localhost:5200'
          # token: ${{ secrets.GITHUB_TOKEN }}
          # docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          # rules_file_name: '.zap/rules.tsv'
          # cmd_options: '-a'

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-scan-results
          path: zap_scan