name: CI/CD .Net Core (ACI)

on:
  workflow_dispatch:
  # pull_request:
    # branches: [ main ]
  push:
    # branches: [ main ]
    paths: 
      - .github/workflows/ci-cd.yml
      - src/**

env:
  registry_name: lfraileacr.azurecr.io
  repository_name: eshop-web-api

jobs:
  build-ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
        version: latest

    - name: Build with dotnet
      run: dotnet build ./eShopOnWeb.sln --configuration Release
    
    - name: Test with dotnet
      run: dotnet test ./eShopOnWeb.sln --configuration Release

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        registry: ${{ env.registry_name }}
        username: ${{ secrets.ACR_USER_NAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        pull: true
        push: true
        file: src/PublicApi/Dockerfile
        tags: ${{ env.registry_name }}/${{ env.repository_name }}:${{ github.sha }}    

  deploydev:
    #if: github.ref != 'refs/heads/main'
    needs: 
      - build-ci

    runs-on: ubuntu-latest
    environment: dockerwebappdev
    env:
      RESOURCE_GROUP: NetCore_GIthubCI_CD_RG
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az account show
            az container create \
              --resource-group ${{ env.RESOURCE_GROUP }} \
              --name eshopwebdemoapidev \
              --image ${{ env.registry_name }}/${{ env.repository_name }}:${{ github.sha }}  \
              --dns-name-label aci-eShopWebDemoApi \
              --ports 80 \
              --registry-login-server ${{ env.registry_name }} \
              --registry-username ${{ secrets.ACR_USER_NAME }} \
              --registry-password ${{ secrets.ACR_PASSWORD }} \
              --environment-variable ConnectionStrings__CatalogConnection="${{ secrets.CATALOG_DB_CONNSTRING }}" ConnectionStrings__IdentityConnection="${{ secrets.IDENTITY_DB_CONNSTRING }}"
