name: Docker Build and Push

on:
# TODO: add additional triggers
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - Web
          - PublicApi
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # TODO: change auth to use GitHub app instead of PAT
    - name: Login to ${{ env.REGISTRY }}
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.RPOC_PAT }}

    - name: Convert image name to lowercase
      run: echo "IMAGE_NAME=$(echo "${{ github.repository }}/${{ matrix.image }}" | awk '{print tolower($0)}')" >> $GITHUB_ENV

    # TODO: add docker/metadata-action to apply tags based on branch, env, etc.
    # TODO: consider project structure, where dockerfile might be, how devs might provide manifests, etc.
    - name: Build Docker image for Web
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./src/${{ matrix.image }}/Dockerfile
        push: false
        tags: ghcr.io/${{ env.IMAGE_NAME }}:latest
        labels: |
          org.opencontainers.image.source=https://github.com/${{ github.repository }}

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      continue-on-error: true
      with:
        scan-type: 'image'
        scanners: 'vuln,secret'
        image-ref: 'ghcr.io/${{ env.IMAGE_NAME }}:latest'
        format: 'github'
        # output: 'trivy-results.sarif'
        exit-code: '1'
        ignore-unfixed: false
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'
        github-pat: ${{ secrets.RPOC_PAT }}
      env:
        TRIVY_USERNAME: ${{ github.actor }}
        TRIVY_PASSWORD: ${{ secrets.RPOC_PAT }}

    # - name: Run Trivy vulnerability scanner (continue on error)
    #   if: github.ref != 'refs/heads/main'
    #   continue-on-error: true
    #   uses: aquasecurity/trivy-action@master
    #   with:
    #     # ...
    #     exit-code: '1'
    #   # ...

    # Not required when using format: 'github' option in the Trivy action
    # - name: Upload Trivy scan results to GitHub Security tab
    #   uses: github/codeql-action/upload-sarif@v2
    #   if: always()
    #   with:
    #     sarif_file: 'trivy-results.sarif'